#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-html-pipeline
Version  : 2.4.2
Release  : 9
URL      : https://rubygems.org/downloads/html-pipeline-2.4.2.gem
Source0  : https://rubygems.org/downloads/html-pipeline-2.4.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rdoc

%description
# HTML::Pipeline [![Build Status](https://travis-ci.org/jch/html-pipeline.svg?branch=master)](https://travis-ci.org/jch/html-pipeline)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n html-pipeline-2.4.2
gem spec %{SOURCE0} -l --ruby > rubygem-html-pipeline.gemspec

%build
export LANG=C
gem build rubygem-html-pipeline.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
html-pipeline-2.4.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/html-pipeline-2.4.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/Appraisals
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/bin/html-pipeline
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/html-pipeline.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/@mention_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/absolute_source_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/autolink_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/body_content.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/camo_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/email_reply_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/emoji_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/https_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/image_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/image_max_width_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/markdown_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/plain_text_input_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/sanitization_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/syntax_highlight_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/text_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/textile_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/toc_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-2.4.2/lib/html/pipeline/version.rb
/usr/lib64/ruby/gems/2.3.0/specifications/html-pipeline-2.4.2.gemspec
