#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-html-pipeline
Version  : 1.11.0
Release  : 7
URL      : https://rubygems.org/downloads/html-pipeline-1.11.0.gem
Source0  : https://rubygems.org/downloads/html-pipeline-1.11.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-rdoc

%description
# HTML::Pipeline [![Build Status](https://secure.travis-ci.org/jch/html-pipeline.png)](http://travis-ci.org/jch/html-pipeline)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n html-pipeline-1.11.0
gem spec %{SOURCE0} -l --ruby > rubygem-html-pipeline.gemspec

%build
gem build rubygem-html-pipeline.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
html-pipeline-1.11.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/html-pipeline-1.11.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/bin/html-pipeline
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/html-pipeline.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/@mention_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/absolute_source_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/autolink_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/body_content.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/camo_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/email_reply_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/emoji_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/https_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/image_max_width_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/markdown_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/plain_text_input_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/sanitization_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/syntax_highlight_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/text_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/textile_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/toc_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/lib/html/pipeline/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/script/package
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/script/release
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/helpers/mocked_instrumentation_service.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/html/pipeline/absolute_source_filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/html/pipeline/autolink_filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/html/pipeline/camo_filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/html/pipeline/emoji_filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/html/pipeline/https_filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/html/pipeline/image_max_width_filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/html/pipeline/markdown_filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/html/pipeline/mention_filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/html/pipeline/plain_text_input_filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/html/pipeline/sanitization_filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/html/pipeline/syntax_highlight_filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/html/pipeline/toc_filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/html/pipeline_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/html-pipeline-1.11.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/html-pipeline-1.11.0.gemspec
