#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-html-pipeline
Version  : 1.11.0
Release  : 5
URL      : https://rubygems.org/downloads/html-pipeline-1.11.0.gem
Source0  : https://rubygems.org/downloads/html-pipeline-1.11.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-rdoc

%description
# HTML::Pipeline [![Build Status](https://secure.travis-ci.org/jch/html-pipeline.png)](http://travis-ci.org/jch/html-pipeline)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n html-pipeline-1.11.0
gem spec %{SOURCE0} -l --ruby > rubygem-html-pipeline.gemspec

%build
gem build rubygem-html-pipeline.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
html-pipeline-1.11.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/html-pipeline-1.11.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/AbsoluteSourceFilter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/AbsoluteSourceFilter/cdesc-AbsoluteSourceFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/AbsoluteSourceFilter/image_base_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/AbsoluteSourceFilter/image_subpage_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/AutolinkFilter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/AutolinkFilter/cdesc-AutolinkFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/BodyContent/cdesc-BodyContent.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/BodyContent/document-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/BodyContent/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/BodyContent/output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/BodyContent/result-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/CamoFilter/asset_host_whitelisted%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/CamoFilter/asset_proxy_enabled%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/CamoFilter/asset_proxy_host-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/CamoFilter/asset_proxy_secret_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/CamoFilter/asset_proxy_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/CamoFilter/asset_proxy_whitelist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/CamoFilter/asset_url_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/CamoFilter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/CamoFilter/cdesc-CamoFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/CamoFilter/hexencode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/CamoFilter/validate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/EmailReplyFilter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/EmailReplyFilter/cdesc-EmailReplyFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/EmojiFilter/asset_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/EmojiFilter/asset_root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/EmojiFilter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/EmojiFilter/cdesc-EmojiFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/EmojiFilter/emoji_filename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/EmojiFilter/emoji_image_filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/EmojiFilter/emoji_names-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/EmojiFilter/emoji_pattern-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/EmojiFilter/emoji_pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/EmojiFilter/emoji_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/EmojiFilter/validate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/InvalidDocumentException/cdesc-InvalidDocumentException.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/base_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/call-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/cdesc-Filter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/current_user-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/doc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/has_ancestor%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/html-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/needs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/parse_html-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/repository-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/result-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/search_text_nodes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/to_document-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/to_html-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/Filter/validate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/HttpsFilter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/HttpsFilter/cdesc-HttpsFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/HttpsFilter/http_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/HttpsFilter/validate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/ImageMaxWidthFilter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/ImageMaxWidthFilter/cdesc-ImageMaxWidthFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/ImageMaxWidthFilter/link_image-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/MarkdownFilter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/MarkdownFilter/cdesc-MarkdownFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/MarkdownFilter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/MentionFilter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/MentionFilter/cdesc-MentionFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/MentionFilter/info_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/MentionFilter/link_to_mention_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/MentionFilter/link_to_mentioned_user-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/MentionFilter/mention_link_filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/MentionFilter/mentioned_logins_in-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/PlainTextInputFilter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/PlainTextInputFilter/cdesc-PlainTextInputFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/SanitizationFilter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/SanitizationFilter/cdesc-SanitizationFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/SanitizationFilter/whitelist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/SyntaxHighlightFilter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/SyntaxHighlightFilter/cdesc-SyntaxHighlightFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/SyntaxHighlightFilter/highlight_with_timeout_handling-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/TableOfContentsFilter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/TableOfContentsFilter/cdesc-TableOfContentsFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/TextFilter/cdesc-TextFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/TextFilter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/TextFilter/text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/TextileFilter/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/TextileFilter/cdesc-TextileFilter.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/cdesc-Pipeline.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/default_instrumentation_service-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/default_payload-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/filters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/instrument-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/instrumentation_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/instrumentation_service-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/perform_filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/setup_instrumentation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/to_document-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/Pipeline/to_html-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/HTML/cdesc-HTML.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/Nokogiri/XML/Node/cdesc-Node.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/Nokogiri/XML/Node/replace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/Nokogiri/XML/Node/replace_with_encoding_fix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/Nokogiri/XML/Node/replace_without_encoding_fix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/Nokogiri/XML/Node/swap-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/Nokogiri/XML/cdesc-XML.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/Nokogiri/cdesc-Nokogiri.ri
/usr/lib64/ruby/gems/2.2.0/doc/html-pipeline-1.11.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/bin/html-pipeline
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/html-pipeline.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/@mention_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/absolute_source_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/autolink_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/body_content.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/camo_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/email_reply_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/emoji_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/https_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/image_max_width_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/markdown_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/plain_text_input_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/sanitization_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/syntax_highlight_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/text_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/textile_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/toc_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/lib/html/pipeline/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/script/package
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/script/release
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/helpers/mocked_instrumentation_service.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/html/pipeline/absolute_source_filter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/html/pipeline/autolink_filter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/html/pipeline/camo_filter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/html/pipeline/emoji_filter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/html/pipeline/https_filter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/html/pipeline/image_max_width_filter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/html/pipeline/markdown_filter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/html/pipeline/mention_filter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/html/pipeline/plain_text_input_filter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/html/pipeline/sanitization_filter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/html/pipeline/syntax_highlight_filter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/html/pipeline/toc_filter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/html/pipeline_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/html-pipeline-1.11.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/html-pipeline-1.11.0.gemspec
